-- =====================================================
-- AquaCollectr — Species Seed Data
-- Run AFTER 001_initial_schema.sql
-- =====================================================

-- ========== FISH — Beginner Staples ==========
INSERT INTO public.species (common_name, scientific_name, category, max_size_cm, min_tank_gallons, temp_min_c, temp_max_c, ph_min, ph_max, aggression_level, care_difficulty, swim_zone, notes) VALUES
('Betta / Siamese Fighting Fish', 'Betta splendens', 'fish', 6, 5, 24, 30, 6.0, 8.0, 'semi-aggressive', 'beginner', 'top/middle', 'Males are territorial and must be kept singly. Females can sometimes coexist in sororities. Labyrinth breather — needs surface access. Stunning fin varieties.'),
('Guppy', 'Poecilia reticulata', 'fish', 5, 10, 22, 28, 6.8, 7.8, 'peaceful', 'beginner', 'top/middle', 'Prolific livebearers with spectacular male coloration. Extremely hardy. Keep 2-3 females per male to reduce stress.'),
('Green Swordtail', 'Xiphophorus hellerii', 'fish', 14, 20, 22, 28, 7.0, 8.4, 'peaceful', 'beginner', 'middle', 'Males have elongated lower tail "sword." Active swimmers needing room. Can be mildly aggressive toward each other.'),
('Southern Platy', 'Xiphophorus maculatus', 'fish', 7, 10, 20, 26, 7.0, 8.0, 'peaceful', 'beginner', 'middle', 'Cheerful, easy livebearers in dozens of color morphs. Great community fish for beginners.'),
('Molly', 'Poecilia sphenops', 'fish', 12, 20, 22, 28, 7.0, 8.5, 'peaceful', 'beginner', 'middle', 'Hardy livebearers available in black, dalmatian, gold, silver, and balloon varieties. Tolerate slightly brackish water.'),
('Sailfin Molly', 'Poecilia velifera', 'fish', 15, 30, 24, 28, 7.5, 8.5, 'peaceful', 'easy', 'middle', 'Larger molly with spectacular dorsal sail in males. Appreciates some salt in water. Needs more space than common mollies.'),
('Neon Tetra', 'Paracheirodon innesi', 'fish', 4, 10, 20, 26, 6.0, 7.0, 'peaceful', 'beginner', 'middle', 'Classic schooling fish with iridescent blue and red stripe. Keep in groups of 8+. Sensitive to sudden water changes.'),
('Cardinal Tetra', 'Paracheirodon axelrodi', 'fish', 5, 10, 23, 28, 5.0, 7.0, 'peaceful', 'easy', 'middle', 'Similar to neons but with full-length red stripe. Prefers soft, acidic water. Wild-caught specimens need careful acclimation.'),
('White Cloud Mountain Minnow', 'Tanichthys albonubes', 'fish', 4, 10, 15, 22, 6.0, 8.0, 'peaceful', 'beginner', 'top/middle', 'Subtropical coldwater fish — no heater needed in most homes. Hardy, colorful, and easy to breed. Great nano tank fish.'),
('Zebra Danio', 'Danio rerio', 'fish', 5, 10, 18, 26, 6.0, 8.0, 'peaceful', 'beginner', 'top/middle', 'Extremely hardy striped fish. Excellent for cycling new tanks. Very active, zippy swimmer. Also available in longfin and GloFish variants.'),
('Bronze Corydoras', 'Corydoras aeneus', 'fish', 7, 15, 22, 27, 6.0, 8.0, 'peaceful', 'beginner', 'bottom', 'Armored catfish that schools along the bottom. Keep on sand substrate in groups of 6+. Entertaining foragers.'),
('Peppered Corydoras', 'Corydoras paleatus', 'fish', 7, 15, 18, 25, 6.0, 7.5, 'peaceful', 'beginner', 'bottom', 'Hardy coldwater-tolerant cory. Spotted pattern. One of the easiest corydoras species. Prefers cooler water than most tropicals.'),
('Bristlenose Pleco', 'Ancistrus spp.', 'fish', 13, 25, 23, 27, 6.0, 7.5, 'peaceful', 'beginner', 'bottom', 'Best algae eater for most tanks. Males grow bushy nose tentacles. Stays manageable unlike common plecos. Needs driftwood.'),
('Otocinclus Catfish', 'Otocinclus spp.', 'fish', 5, 10, 22, 27, 6.0, 7.5, 'peaceful', 'intermediate', 'bottom', 'Tiny, gentle algae grazer. Keep in groups of 6+. Sensitive to water quality — only add to established tanks. Supplement with blanched veggies.'),
('Freshwater Angelfish', 'Pterophyllum scalare', 'fish', 15, 30, 24, 30, 6.0, 7.5, 'semi-aggressive', 'easy', 'middle', 'Elegant, tall-bodied cichlid. Can be territorial when breeding. Needs vertical space. Will eat tiny tankmates like neon tetras.'),
('Three-Spot Gourami', 'Trichopodus trichopterus', 'fish', 15, 30, 24, 28, 6.0, 8.0, 'semi-aggressive', 'beginner', 'top/middle', 'Labyrinth fish available in blue, gold, and opaline morphs. Males can be aggressive to each other. Hardy and forgiving.'),
('Bleeding Heart Tetra', 'Hyphessobrycon erythrostigma', 'fish', 8, 20, 23, 28, 6.0, 7.0, 'peaceful', 'easy', 'middle', 'Deep-bodied tetra with distinctive red "heart" spot. Prefers soft water and subdued lighting. School of 6+.'),
('Harlequin Rasbora', 'Trigonostigma heteromorpha', 'fish', 5, 10, 22, 28, 6.0, 7.5, 'peaceful', 'beginner', 'middle', 'Elegant orange-pink body with black wedge marking. Peaceful, easy schooler. One of the best community fish.'),
('Scissortail Rasbora', 'Rasbora trilineata', 'fish', 15, 30, 22, 26, 6.0, 7.5, 'peaceful', 'beginner', 'middle/top', 'Larger rasbora with distinctive forked tail markings. Active swimmer needing a long tank. Hardy and peaceful.'),
('Cherry Barb', 'Puntius titteya', 'fish', 5, 10, 23, 27, 6.0, 7.0, 'peaceful', 'beginner', 'middle/bottom', 'Males turn deep cherry red when in breeding color. Very peaceful barb — nothing like tiger barbs. Hardy and undemanding.'),
('Common Goldfish', 'Carassius auratus', 'fish', 30, 40, 10, 24, 6.0, 8.0, 'peaceful', 'beginner', 'middle', 'NOT a tropical fish — needs cooler water (no heater). Gets very large. Best in ponds or large tanks. Extremely long-lived (20+ years).'),
('Comet Goldfish', 'Carassius auratus (comet)', 'fish', 30, 55, 10, 24, 6.0, 8.0, 'peaceful', 'beginner', 'middle', 'Sleek, long-tailed goldfish variety. Faster swimmer than fancies. Needs large tank or pond. Do NOT keep in bowls.'),
('Fantail Goldfish', 'Carassius auratus (fantail)', 'fish', 20, 30, 10, 24, 6.0, 8.0, 'peaceful', 'easy', 'middle', 'Fancy goldfish with double tail. Slower swimmer, keep away from fast fish. Cooler water, high filtration. Do not mix with single-tails.'),

-- ========== FISH — Intermediate / Advanced ==========
('Apistogramma', 'Apistogramma spp.', 'fish', 8, 20, 24, 29, 5.0, 7.0, 'semi-aggressive', 'intermediate', 'bottom/middle', 'Colorful dwarf cichlids. Males are territorial. Need soft, acidic water and a well-planted tank with caves. Many beautiful species.'),
('German Blue Ram', 'Mikrogeophagus ramirezi', 'fish', 7, 20, 26, 30, 5.5, 7.0, 'peaceful', 'intermediate', 'bottom/middle', 'Stunning dwarf cichlid with electric blue and gold. Needs warm, pristine water. Sensitive to poor water quality. Short-lived (2-3 years).'),
('Yoyo / Striata Loach', 'Botia striata', 'fish', 10, 30, 23, 27, 6.0, 7.5, 'peaceful', 'intermediate', 'bottom', 'Attractive striped loach. Active, playful personality. Excellent snail control. Keep in groups of 4+. Needs hiding spots.'),
('Upside-Down Catfish', 'Synodontis nigriventris', 'fish', 10, 30, 22, 27, 6.0, 7.5, 'peaceful', 'easy', 'middle/bottom', 'Swims inverted to feed from surface and underside of decor. Fascinating behavior. Nocturnal — provide caves and dim lighting.'),
('Boesemani Rainbowfish', 'Melanotaenia boesemani', 'fish', 12, 30, 24, 28, 7.0, 8.0, 'peaceful', 'intermediate', 'middle/top', 'Split blue/orange coloring that intensifies with age. Males are spectacular. Active, needs swimming room and good filtration.'),
('Threadfin Rainbowfish', 'Iriatherina werneri', 'fish', 5, 10, 24, 28, 5.5, 7.5, 'peaceful', 'intermediate', 'middle/top', 'Delicate nano rainbow with thread-like fin extensions. Peaceful and shy — keep with gentle tankmates only.'),
('Discus', 'Symphysodon spp.', 'fish', 20, 55, 28, 32, 5.5, 7.0, 'peaceful', 'advanced', 'middle', 'The "king of the aquarium." Demands pristine water, high temps, and a varied diet. Keep in groups. Expensive but breathtaking.'),
('Clown Killifish', 'Epiplatys annulatus', 'fish', 4, 5, 23, 27, 6.0, 7.0, 'peaceful', 'intermediate', 'top', 'Tiny surface-dwelling killifish with rocket-shaped tail. Beautiful micro predator. Great for nano planted tanks.'),
('Gardneri Killifish', 'Fundulopanchax gardneri', 'fish', 6, 10, 22, 26, 6.0, 7.5, 'semi-aggressive', 'intermediate', 'top/middle', 'Brilliantly colored killifish. Males are stunning blue/red. Can be jumpy — tight-fitting lid essential. Males territorial.'),
('Endlers Livebearer', 'Poecilia wingei', 'fish', 4, 5, 24, 30, 7.0, 8.5, 'peaceful', 'beginner', 'top/middle', 'Tiny, vivid cousin of the guppy. Males are spectacularly colored. Prolific breeders. Keep pure from guppy hybridization.'),

-- ========== FISH — Large / Advanced ==========
('Oscar', 'Astronotus ocellatus', 'fish', 35, 75, 23, 28, 6.0, 8.0, 'aggressive', 'intermediate', 'middle', 'Intelligent, personable large cichlid with dog-like personality. Grows fast, messy eater. Needs massive tank and powerful filtration.'),
('Red-Tailed Black Shark', 'Epalzeorhynchos bicolor', 'fish', 15, 55, 22, 27, 6.5, 7.5, 'aggressive', 'intermediate', 'bottom/middle', 'Striking jet-black body with vivid red tail. Highly territorial — one per tank. Chases similar-looking fish aggressively.'),
('Red-Bellied Pacu', 'Piaractus brachypomus', 'fish', 60, 250, 24, 28, 6.0, 7.5, 'peaceful', 'advanced', 'middle', 'Often mis-sold as a "vegetarian piranha." Gets ENORMOUS — needs a pond-sized setup. Do not impulse buy! Herbivore.'),
('Silver Arowana', 'Osteoglossum bicirrhosum', 'fish', 90, 300, 24, 30, 6.0, 7.0, 'aggressive', 'advanced', 'top', 'Massive, prehistoric surface predator. Jumps out of tanks — heavy, tight lid mandatory. Only for expert fishkeepers with enormous setups.'),
('Convict Cichlid', 'Amatitlania nigrofasciata', 'fish', 15, 30, 20, 28, 6.0, 8.0, 'aggressive', 'beginner', 'middle/bottom', 'Hardy, prolific breeder. Very aggressive when guarding fry. Black and white striped. Good beginner cichlid if you want personality.'),
('Jack Dempsey Cichlid', 'Rocio octofasciata', 'fish', 25, 55, 22, 28, 6.5, 8.0, 'aggressive', 'intermediate', 'middle/bottom', 'Beautiful iridescent spots on dark body. Named after the boxer — appropriately aggressive. Electric Blue variant is popular.'),
('Firemouth Cichlid', 'Thorichthys meeki', 'fish', 17, 30, 23, 28, 6.5, 8.0, 'semi-aggressive', 'easy', 'middle/bottom', 'Flares bright red throat in territorial displays. Less aggressive than many Central American cichlids. Good "gateway" cichlid.');

-- ========== PLANTS ==========
INSERT INTO public.species (common_name, scientific_name, category, max_size_cm, min_tank_gallons, temp_min_c, temp_max_c, ph_min, ph_max, aggression_level, care_difficulty, swim_zone, notes) VALUES
('Java Fern', 'Leptochilus pteropus', 'plant', 30, 5, 20, 28, 6.0, 7.5, 'peaceful', 'beginner', NULL, 'Bulletproof epiphyte. Attach to rocks/wood — do NOT bury the rhizome or it will rot. Low light tolerant. Propagates via plantlets on leaves.'),
('Java Moss', 'Taxiphyllum barbieri', 'plant', 10, 1, 15, 30, 5.0, 8.0, 'peaceful', 'beginner', NULL, 'Versatile moss that grows on anything. Great for shrimp hiding spots and fry cover. Tie or glue to hardscape. Trim regularly.'),
('Anubias Barteri', 'Anubias barteri', 'plant', 25, 5, 22, 28, 6.0, 7.5, 'peaceful', 'beginner', NULL, 'Slow-growing, nearly indestructible. Attach to hardscape — never bury rhizome. Prone to algae on leaves in high light.'),
('Anubias Nana', 'Anubias barteri var. nana', 'plant', 12, 5, 22, 28, 6.0, 7.5, 'peaceful', 'beginner', NULL, 'Compact version of Anubias barteri. Perfect foreground/midground plant. Extremely slow growing but bulletproof. Great for beginners.'),
('Cryptocoryne Wendtii', 'Cryptocoryne wendtii', 'plant', 20, 5, 22, 28, 6.0, 8.0, 'peaceful', 'beginner', NULL, 'Versatile crypt in green, red, and brown varieties. May "melt" when transplanted but recovers from roots. Low-tech staple.'),
('Cryptocoryne Parva', 'Cryptocoryne parva', 'plant', 5, 5, 22, 28, 6.0, 7.5, 'peaceful', 'intermediate', NULL, 'Smallest crypt species. Very slow-growing carpeting plant. Needs patience — takes months to fill in. No CO2 required but helps.'),
('Vallisneria', 'Vallisneria spiralis', 'plant', 60, 10, 18, 28, 6.5, 8.5, 'peaceful', 'beginner', NULL, 'Tall, grass-like background plant. Sends out runners rapidly. Very easy — just plant and watch it spread. Dislikes liquid carbon products.'),
('Giant Vallisneria', 'Vallisneria americana', 'plant', 100, 20, 18, 28, 6.5, 8.5, 'peaceful', 'beginner', NULL, 'Very tall background plant with ribbon-like leaves. Can reach the surface of deep tanks. Spreads aggressively via runners.'),
('Amazon Sword', 'Echinodorus spp.', 'plant', 50, 20, 22, 28, 6.5, 7.5, 'peaceful', 'beginner', NULL, 'Large, impressive rosette plant. Heavy root feeder — use root tabs. Great centerpiece. Gets big, so give it space.'),
('Water Wisteria', 'Hygrophila difformis', 'plant', 50, 10, 24, 28, 6.5, 7.5, 'peaceful', 'beginner', NULL, 'Fast-growing stem plant with lacy leaves. Changes leaf shape depending on emersed/submersed growth. Excellent nutrient sponge.'),
('Ludwigia Repens', 'Ludwigia repens', 'plant', 50, 10, 20, 28, 6.0, 8.0, 'peaceful', 'beginner', NULL, 'Red/green stem plant that colors up under strong light. Easy to propagate — just trim and replant tops. Great for color contrast.'),
('Water Hyssop', 'Bacopa monnieri', 'plant', 30, 5, 22, 28, 6.0, 8.0, 'peaceful', 'beginner', NULL, 'Upright stem plant with rounded leaves. Very undemanding. Can grow emersed. Also used as an herbal supplement (Brahmi).'),
('Hornwort', 'Ceratophyllum demersum', 'plant', 60, 5, 15, 30, 6.0, 7.5, 'peaceful', 'beginner', NULL, 'Fast-growing stem plant. Can float or be weighted down. Excellent nutrient absorber and oxygenator. Sheds needles if unhappy.'),
('Duckweed', 'Lemna minor', 'plant', 1, 1, 10, 30, 5.0, 9.0, 'peaceful', 'beginner', NULL, 'Tiny floating plant that multiplies explosively. Great nutrient absorber but nearly impossible to eradicate once introduced. You have been warned.'),
('Amazon Frogbit', 'Limnobium laevigatum', 'plant', 5, 5, 22, 28, 6.0, 7.5, 'peaceful', 'beginner', NULL, 'Floating plant with round leaves and long roots. Provides shade and cover. Absorbs excess nutrients. Keep surface movement low.'),
('Bucephalandra', 'Bucephalandra spp.', 'plant', 10, 5, 22, 28, 5.5, 7.5, 'peaceful', 'intermediate', NULL, 'Slow-growing rheophyte with metallic sheen on leaves. Attach to hardscape like Anubias. Many rare and collectible varieties.'),
('Christmas Moss', 'Vesicularia montagnei', 'plant', 8, 1, 20, 28, 5.5, 7.5, 'peaceful', 'easy', NULL, 'Triangular frond pattern resembling Christmas tree branches. Great on mesh for walls or carpets. Slightly more demanding than Java Moss.'),
('Flame Moss', 'Taxiphyllum sp. "flame"', 'plant', 8, 1, 20, 28, 5.5, 7.5, 'peaceful', 'easy', NULL, 'Grows upright in flame-like pattern. Unique texture for aquascaping. Attach to vertical surfaces for best effect.');

-- ========== INVERTEBRATES ==========
INSERT INTO public.species (common_name, scientific_name, category, max_size_cm, min_tank_gallons, temp_min_c, temp_max_c, ph_min, ph_max, aggression_level, care_difficulty, swim_zone, notes) VALUES
('Cherry Shrimp', 'Neocaridina davidi', 'invertebrate', 3, 5, 18, 28, 6.5, 8.0, 'peaceful', 'beginner', 'bottom', 'Hardy dwarf shrimp in red, blue, orange, yellow, and more color variants. Prolific breeders. Excellent algae and detritus cleaners.'),
('Amano Shrimp', 'Caridina multidentata', 'invertebrate', 5, 10, 20, 28, 6.5, 7.5, 'peaceful', 'beginner', 'bottom', 'The best algae-eating shrimp — named after aquascaper Takashi Amano. Larger than cherry shrimp. Cannot breed in freshwater.'),
('Ghost Shrimp', 'Palaemonetes paludosus', 'invertebrate', 5, 5, 18, 28, 7.0, 8.0, 'peaceful', 'beginner', 'bottom', 'Nearly transparent, inexpensive shrimp. Great cleaners and fun to observe eating. Often sold as feeder shrimp but make great pets.'),
('Nerite Snail', 'Neritina spp.', 'invertebrate', 3, 5, 22, 28, 7.0, 8.5, 'peaceful', 'beginner', 'bottom', 'Best algae-eating snail. Will NOT reproduce in freshwater (eggs won''t hatch). Available in zebra, tiger, horned, olive, and spotted varieties.'),
('Mystery Snail', 'Pomacea bridgesii', 'invertebrate', 6, 5, 20, 28, 7.0, 8.0, 'peaceful', 'beginner', 'bottom', 'Large, colorful snail in gold, ivory, blue, magenta, and purple. Lays pink egg clutches above waterline. Fun personality.'),
('Ramshorn Snail', 'Planorbella duryi', 'invertebrate', 3, 1, 18, 28, 7.0, 8.0, 'peaceful', 'beginner', 'bottom', 'Flat spiral-shelled snail in red, blue, and leopard varieties. Can reproduce quickly — some see them as pests, others love them.'),
('Bladder Snail', 'Physella acuta', 'invertebrate', 1, 1, 15, 28, 6.5, 8.0, 'peaceful', 'beginner', 'bottom', 'Tiny hitchhiker snail. Reproduces rapidly. Excellent detritus cleaner. Population self-regulates with food availability. Free cleanup crew!'),
('Malaysian Trumpet Snail', 'Melanoides tuberculata', 'invertebrate', 3, 1, 18, 28, 7.0, 8.0, 'peaceful', 'beginner', 'bottom', 'Burrowing snail that aerates substrate and eats leftover food. Mostly nocturnal. Livebearing — population can boom. Great for planted tanks.');
